### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by robinsonkwame** [crmne/cookiecutter-modern-datascience#6]
Love the idea of this repo, is it still maintained?

**Comment by crmne** [comment]
Thank you, @robinsonkwame! Sure, I'll update the few explicit versions in the template sometime soon.

Apart from that, do you have any other suggestions for improvements?

**Comment by crmne** [comment]
Hey @robinsonkwame I just pushed a bunch of updates to the repo. Thank you for your interest! Feel free to make new issues for each suggestion you have :)
